# Mnist Handwrite

[Deep Learning 3 - Download the MNIST, handwritten digit dataset](https://schwalbe10.github.io/thinkage/2017/03/05/mnist.html)

In [17]:
import os

data_sources = {
    "training_images": os.path.join('dataset/mnist_lecun', "train-images-idx3-ubyte.gz"),  # 60,000 training images.
    "test_images":  os.path.join('dataset/mnist_lecun',"t10k-images-idx3-ubyte.gz"),  # 10,000 test images.
    "training_labels":  os.path.join('dataset/mnist_lecun',"train-labels-idx1-ubyte.gz"),  # 60,000 training labels.
    "test_labels":  os.path.join('dataset/mnist_lecun',"t10k-labels-idx1-ubyte.gz"),  # 10,000 test labels.
}

data_sources["training_images"]

'dataset/mnist_lecun/train-images-idx3-ubyte.gz'

In [18]:
import gzip


def read_gzip(path):
    with gzip.open(path, 'rb') as fd:
        return fd.read()

def load_images(path):
    return np.frombuffer(read_gzip(path), np.uint8, offset=8)

def load_labels(path):
    return np.frombuffer(read_gzip(path), np.uint8, offset=16)
    
mnist_dataset = {
    'training_images': load_images(data_sources['training_images']),
    'test_images': load_images(data_sources['test_images']),
    'training_labels': load_labels(data_sources['training_labels']),
    'test_labels': load_labels(data_sources['test_labels']),
}

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-ca19cc2d26d3>", line 15, in <module>
    'training_images': load_images(data_sources['training_images']),
  File "<ipython-input-18-ca19cc2d26d3>", line 9, in load_images
    return np.frombuffer(read_gzip(path), np.uint8, offset=8)
  File "<ipython-input-18-ca19cc2d26d3>", line 5, in read_gzip
    with gzip.open(path, 'rb') as fd:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/mnist_lec

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/mnist_lecun/train-images-idx3-ubyte.gz'

In [29]:
a = np.array(((1,2), (3, 4)))
b = np.array(((5,6), (7, 8)))
a

array([[1, 2],
       [3, 4]])

In [30]:
a @ b

array([[19, 22],
       [43, 50]])

In [32]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [33]:
c = np.array([
                       [1,2,3,4],
                       [3,2,1,4],
                       [5,4,6,7],
                       [11,12,13,14]
                      ])
c

array([[ 1,  2,  3,  4],
       [ 3,  2,  1,  4],
       [ 5,  4,  6,  7],
       [11, 12, 13, 14]])

In [34]:
d = np.array([
                             [[2,3],[11,9],[32,21],[28,17]],
                             [[2,3],[1,9],[3,21],[28,7]],
                             [[2,3],[1,9],[3,21],[28,7]],
                            ])
d

array([[[ 2,  3],
        [11,  9],
        [32, 21],
        [28, 17]],

       [[ 2,  3],
        [ 1,  9],
        [ 3, 21],
        [28,  7]],

       [[ 2,  3],
        [ 1,  9],
        [ 3, 21],
        [28,  7]]])

In [35]:
c.shape, d.shape

((4, 4), (3, 4, 2))

In [37]:
c @ d

array([[[232, 152],
        [172, 116],
        [442, 296],
        [962, 652]],

       [[125, 112],
        [123,  76],
        [228, 226],
        [465, 512]],

       [[125, 112],
        [123,  76],
        [228, 226],
        [465, 512]]])

In [39]:
np.dot(c, d)

array([[[232, 152],
        [125, 112],
        [125, 112]],

       [[172, 116],
        [123,  76],
        [123,  76]],

       [[442, 296],
        [228, 226],
        [228, 226]],

       [[962, 652],
        [465, 512],
        [465, 512]]])

In [53]:
np.random.rand(3,1,2)

array([[[0.76656709, 0.94816933]],

       [[0.67999922, 0.18194632]],

       [[0.88726742, 0.0268895 ]]])

In [57]:
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])